AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for creating Lambda function, Glue job, and S3 bucket.'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'my-unique-bucket-name'

  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref MyS3Bucket
        S3Key: 'lambda_function.zip'
      Handler: 'lambda_function.lambda_handler'
      Role: 'arn:aws:iam::123456789012:role/lambda-role'
      Runtime: 'python3.8'

  MyGlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Command:
        Name: 'glueetl'
        ScriptLocation: 's3://my-unique-bucket-name/glue_script.py'
      Role: 'arn:aws:iam::123456789012:role/glue-role'
      DefaultArguments:
        '--job-language': 'python'
      GlueVersion: '1.0'
      MaxCapacity: 2
      MaxRetries: 0
